before_script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt install -yq build-essential cmake git scdoc

build:ubuntu:20.04:
  stage: build
  image: ubuntu:20.04
  artifacts:
    paths:
       - "build/ydotool"
       - "build/ydotoold"
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_FLAGS='-O2' ..
    - make -j2

